device oldestDate and newestDate added to persist device sync progress
internxt/photos-server pull request #19
Opened 2022-01-19 11:46 UTC by carlossalasamper

2022-01-19 11:54 UTC, sraver commented
@carlossalasamper since you are touching here, [this import](https://github.com/internxt/photos-server/blob/master/src/api/devices/controller.ts#L3) seems to be unused, you could remove it :p

Also, seems to be some conflicts on the branch

2022-01-19 12:47 UTC, sraver approved these changes

2022-01-20 16:25 UTC, sg-gs requested changes

2022-01-20 16:25 UTC, sg-gs commented on src/api/photos/controller.ts
> +      return rep.status(500).send({ message: 'Device not found' });
404 better

2022-01-20 16:39 UTC, sg-gs commented on src/api/photos/controller.ts
> +      return rep.status(500).send({ message: 'Device not found' });
Agreed with 400 finally

2022-01-20 16:41 UTC, sg-gs approved these changes

2022-01-20 16:44 UTC, merged